export default {
  login: "vatari",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/vatari",
  html_url: "https://github.com/vatari",
  followers_url: "https://api.github.com/users/vatari/followers",
  following_url: "https://api.github.com/users/vatari/following{/other_user}",
  gists_url: "https://api.github.com/users/vatari/gists{/gist_id}",
  starred_url: "https://api.github.com/users/vatari/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/vatari/subscriptions",
  organizations_url: "https://api.github.com/users/vatari/orgs",
  repos_url: "https://api.github.com/users/vatari/repos",
  events_url: "https://api.github.com/users/vatari/events{/privacy}",
  received_events_url: "https://api.github.com/users/vatari/received_events",
  type: "User",
  site_admin: false,
  name: "Petar Zhelev",
  company: "matrix",
  location: "Varna",
  email: null,
  hireable: null,
  bio: "React Entusiast",
  twitter_username: "Yngtar",
  public_repos: 25,
  public_gists: 0,
  followers: 7,
  following: 0,
  created_at: "2015-08-06T06:48:23Z",
  updated_at: "2023-07-08T05:01:32Z",
};
