export default {
  login: "Vatari",
  id: 8471918,
  node_id: "MDQ6VXNlcjg0NzE5MTg=",
  avatar_url: "https://avatars.githubusercontent.com/u/8471918?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Vatari",
  html_url: "https://github.com/Vatari",
  followers_url: "https://api.github.com/users/Vatari/followers",
  following_url: "https://api.github.com/users/Vatari/following{/other_user}",
  gists_url: "https://api.github.com/users/Vatari/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Vatari/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Vatari/subscriptions",
  organizations_url: "https://api.github.com/users/Vatari/orgs",
  repos_url: "https://api.github.com/users/Vatari/repos",
  events_url: "https://api.github.com/users/Vatari/events{/privacy}",
  received_events_url: "https://api.github.com/users/Vatari/received_events",
  type: "User",
  site_admin: false,
  name: "Petar Zhelev",
  company: null,
  blog: "",
  location: "Bulgaria",
  email: null,
  hireable: true,
  bio: null,
  twitter_username: null,
  public_repos: 22,
  public_gists: 5,
  followers: 7,
  following: 5,
  created_at: "2014-08-17T15:33:06Z",
  updated_at: "2023-06-26T06:48:47Z",
};
